In [ ]:
#INDRODUCTION TO NUMPY
print("INDRODUCTION TO NUMPY")
import numpy as np
print(np.__version__)
arr=[1,2,3,4]
arr=arr*2
print("\n",arr)

arr2=[1,2,3,4]
arr2=np.array(arr2)
arr2=arr2*2
print("\n",arr2)


INDRODUCTION TO NUMPY
2.4.5

 [1, 2, 3, 4, 1, 2, 3, 4]

 [2 4 6 8]


In [ ]:
#MULTI-DIMENSIONAL ARRAY
print("MULTI-DIMENSIONAL ARRAY")

import numpy as np
arr1=np.array('A')
print(f"Arr1 is {arr1.ndim} dimensional array")

print()
arr2=np.array(["A","B","C"])
print(f"Arr2 is {arr2.ndim} dimensional array")
print(f"Arr2 shape is {arr2.shape}")

print()
arr3=np.array([["A","B","C"],["D","E","F"],["G","H","I"]])
print(f'Arr3 is {arr3.ndim} dimensional array')
print(f"Arr3 shape is {arr3.shape}")

print()
arr4=np.array([[["A","B","C"],["D","E","F"],["G","H","I"]],
               [["J","K","L"],["M","N","O"],["P","Q","R"]],
               [["S","T","U"],["V","W","X"],["Y","Z","a"]]])
print(f"Arr4 is {arr4.ndim} dimensional array")
print(f"Array shape is {arr4.shape}")
print(arr4[2,2,0])
print(arr4[1,0,0])

print()
name=arr4[0,0,0]+arr4[0,1,0]+arr4[0,2,1]+arr4[0,2,2]+arr4[1,0,2]
print(f"Your name is: {name}")

Arr1 is 0 dimensional array

Arr2 is 1 dimensional array
Arr2 shape is (3,)

Arr3 is 2 dimensional array
Arr3 shape is (3, 3)

Arr4 is 3 dimensional array
Array shape is (3, 3, 3)
Y
J

Your name is: ADHIL


In [ ]:
#SLICING
print("SLICNG")

import numpy as np
array=np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12],
                [13,14,15,16]])
# Row selection
print("ROW SELECTION")
print(f"a) {array[0:4]}")
print(f"\nb) {array[1:]}")
print(f"\nc) {array[::-1]}")
print(f"\nd) {array[0]}")
print(f"\ne) {array[0::2]}")

#Column selection
print("\nCOLUMN SELECTION:")
print(f"A) {array[:,0]}")
print(f"\nB) {array[:,1:4]}")
print(f"\nC)  {array[:,0::]}")
print(f"\nD) {array[:,::-1]}")

#Row and Column selection
print("Row and COlumn selection")
print(f"1) {array[1:3,1:3]}")
print(f"2) {array[2:,2:]}")

ROW SELECTION
a) [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

b) [[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

c) [[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]

d) [1 2 3 4]

e) [[ 1  2  3  4]
 [ 9 10 11 12]]

COLUMN SELECTION:
A) [ 1  5  9 13]

B) [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]

C)  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

D) [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
Row and COlumn selection
1) [[ 6  7]
 [10 11]]
2) [[11 12]
 [15 16]]


In [ ]:
#ARITHMETIC OPERATIONS
print("ARITHMETIC OPERATIONS")

import numpy as np
#Scalar arithmetic

array=np.array([1,2,3])
print(array+1)
print(array-1)
print(array*5)
print(array/2)
print(array**3)

#Vectorized math func
print()
arr1=np.array([1,2,3])
print(np.sqrt(arr1))
arr2=np.array([1.01,2.5,3.99])
print(np.round(arr2))#Round off
print(np.ceil(arr2))#Round up
print(np.floor(arr2))#Round down
print(np.pi)

#EXERCISE 1
print()
radii=np.array([1,2,3])
print(f"The area of circle is: {np.pi*radii**2}")

#Element-wise Arithmetic
print()
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(f'Adding:{arr1+arr2}')
print(f'Subtracting:{arr2-arr1}')
print(f'Multiplication:{arr1*arr2}')
print(f"Division:{arr1/arr2}")
print(f"Power:{arr1**arr2}")


#Comparison operation
print()
scores=np.array([91,55,100,73,82,64])
print(scores==100)
scores[scores<60]=0
print(scores)

[2 3 4]
[0 1 2]
[ 5 10 15]
[0.5 1.  1.5]
[ 1  8 27]

[1.         1.41421356 1.73205081]
[1. 2. 4.]
[2. 3. 4.]
[1. 2. 3.]
3.141592653589793

The area of circle is: [ 3.14159265 12.56637061 28.27433388]

Adding:[5 7 9]
Subtracting:[3 3 3]
Multiplication:[ 4 10 18]
Division:[0.25 0.4  0.5 ]
Power:[  1  32 729]

[False False  True False False False]
[ 91   0 100  73  82  64]


In [ ]:
#BRAODCASTING:Broadcasting in NumPy is a feature where NumPy automatically makes arrays compatible for mathematical operations, even when their shapes are different.
#Condition:
#1) The dimensions have the same size
#OR
#2)One of the dimension has the size of 1
import numpy as np
print("BRAODCASTING")
print()

arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9]])
print(arr1.shape)
print(arr2.shape)
print(f"\nResult is: {arr1*arr2}")

BRAODCASTING

(2, 3)
(1, 3)

Result is: [[ 7 16 27]
 [28 40 54]]


In [68]:
#Aggregate function
print("AGGREGATE FUNCTION")
data=np.array([[1,2,3,4,5],
              [6,7,8,9,10]])
print()
print(f"The sum of elements in data is:{np.sum(data)}")
print(f"The average of elements in data is:{np.mean(data)}")
print(f"The SD  is: {np.std(data)}")
print(f"The variance is: {np.var(data)}")
print(f"The Higher element in data is: {np.max(data)}")
print(f"The smallest element in data is: {np.min(data)}")
print(f"The postion of Highest element is: {np.argmax(data)}")
print(f"The position of smallest element is: {np.argmin(data)}")


print()
print(f"The sum of column will be:{np.sum(data, axis=0)}")#add elements in column
print(f"The sum of rows will  be: {np.sum(data, axis=1)}")#add elements in row

AGGREGATE FUNCTION

The sum of elements in data is:55
The average of elements in data is:5.5
The SD  is: 2.8722813232690143
The variance is: 8.25
The Higher element in data is: 10
The smallest element in data is: 1
The postion of Highest element is: 9
The position of smallest element is: 0

The sum of column will be:[ 7  9 11 13 15]
The sum of rows will  be: [15 40]


In [ ]:
#Concatenate along row:(axis=0)   row increases : join arrays vertically
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[4,5],[6,7]])
result=np.concatenate((arr1,arr2),axis=0)
print(result)


print()
#Concatenate along column:(axis=1) column increases : Join array horizontally
arr3=np.array([[1,2],[3,4]])
arr4=np.array([[5,6],[7,8]])
result2=np.concatenate((arr3,arr4),axis=1)
print(result2)

print()
#Stack axis=0:  Array become seperate outer axis:  create new front layer : create new dimension
arr5=np.array([[1,2],[3,4]])
arr6=np.array([[5,6],[7,8]])
result3=np.stack((arr5,arr6),axis=0)
print(result3)


[[1 2]
 [3 4]
 [4 5]
 [6 7]]

[[1 2 5 6]
 [3 4 7 8]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
new_arr=[]
for element in arr:
    if element%2==0:
        new_arr.append(True)
    else:
        new_arr.append(False)
print(new_arr)
even_arr=arr[new_arr]
print(even_arr)

[False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10]
