VECTOR OPERATIONS

In [1]:
#VECTOR ADDITION/SUBTRACTION
v1=[1,2,3]
v2=[4,5,6]
result1=[]
for i in range(len(v1)):
    result1.append(v1[i]+v2[i])
print(f'By adding vectors:{result1}')

result2=[]
for i in  range(len(v2)):
    result2.append(v1[i]-v2[i])
print(f'By subtracting vectors:{result2}')


#SCALAR MULTIPLICATION
#NOTE
scalar=3
result3=[]
for i in v1:
    result3.append(scalar*i)
print(f'Result is:{result3}')

By adding vectors:[5, 7, 9]
By subtracting vectors:[-3, -3, -3]
Result is:[3, 6, 9]


FINDING ANGLE BETWEEN TWO VECTORS

In [2]:
A=[1,2]
B=[4,6]
#cosx=(AB)/(|A||B|)
dot=A[0]*B[0]+A[1]*B[1]
magA=((A[0]**2)+(A[1]**2))**0.5
magB=((B[0]**2)+(B[1]**2))**0.5
cosx=(dot/(magA*magB))
print(f'Cos theta is:{cosx}')
import math
theta=math.degrees(math.acos(cosx))
print(f'Angle bw 2 vectors is:{theta}')

Cos theta is:0.9922778767136677
Angle bw 2 vectors is:7.125016348901757


MATRIX OPERATIONS

In [3]:
A = [
    [1, 2],
    [3, 4]
]
B = [
    [5, 6],
    [7, 8]
]
#MATRIX ADDITION
result=[]
for i in range(len(A)):
    row=[]
    for j in range(len(A[0])):
        row.append(A[i][j]+B[i][j])
    result.append(row)
print(F'By adding Matrices:{result}')

#SCALAR MULTIPLICATION
k=5
result1=[]
for i in range(len(A)):
    row=[]
    for j in range(len(A[0])):
        row.append(k*A[i][j])
    result1.append(row)
print(f'Result is:{result1}')

#MATRIX MULTIPLICATION
result5=[[0,0],
         [0,0]]
for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B)):
            result5[i][j]+=A[i][k]*B[k][j]
print(f'By multiplying 2 matrices:{result5}')




By adding Matrices:[[6, 8], [10, 12]]
Result is:[[5, 10], [15, 20]]
By multiplying 2 matrices:[[19, 22], [43, 50]]


FINDING DETERMINANT AND TRANSPOSE OF A MATRIX

In [ ]:
#DETERMINANT
A=[[1,2],
   [3,4]]
det=[A[0][0]*A[1][1]-A[0][1]*A[1][0]]
print(f'Determinantt is:{det}')

B=[[1,2,3],
   [4,5,6]]

#TRANSPOSE
transpose=[]
for i in range(len(B[0])):
    row=[]
    for j in range(len(B)):
        row.append(B[j][i])
    transpose.append(row)
print(f'Transpose is:{transpose}')


Determinantt is:[-2]
Transpose is:[[1, 4], [2, 5], [3, 6]]


FINDING MINOR, COFACTOR AND INVERSE(IMPORTANT) OF A MATRIX

In [5]:
#MINOR OF ELEMENT A[2][2]
A = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
minora33=[]
row=2
col=2
for i in range(len(A)):
    if i==row:
        continue
    new_row=[]
    for j in range(len(A[0])):
        if j==col:
            continue
        new_row.append(A[i][j])
    minora33.append(new_row)
print(F'Minor Matrix:{minora33}')

minor_9=[A[0][0]*A[1][1]-A[0][1]*A[1][0]]
print(f'Minor of 9 is:{minor_9}')

#COFACTOR
sign=(-1)**(row+col)
cofactor=sign*minor_9
print(f'Cofactor is:{cofactor}')


#FINDING INVERSE OF A MATRIX USING GAUSS JORDAN METHOD IS EASY COMPPARED TO TRADITIONAL METHOD
#GJ method
# A =
# [2 1 1]
# [1 3 2]
# [1 0 0]
#
# I =
# [1 0 0]
# [0 1 0]
# [0 0 1]
#
# Augmented matrix [A | I]
print()
A=[[2,1,1,1,0,0],
   [1,3,2,0,1,0],
   [1,0,0,0,0,1]]
A[2],A[0]=A[0],A[2]

for i in range(len(A[0])):
    A[1][i]=A[1][i]-A[0][i]

for i in range(len(A[0])):
    A[2][i]=A[2][i]-2*A[0][i]

for i in range(len(A[0])):
    A[1][i]=A[1][i]-2*A[2][i]

for i in range(len(A[0])):
    A[2][i]=A[2][i]-A[1][i]

for row in A:
    print(f'After rearranging :{row}')
print()
#[1, 0, 0, 0, 0, 1]
#[0, 1, 0, -2, 1, 3]
#[0, 0, 1, 3, -1, -5]
#This is the result we got and the matrix other than identity matrix is consider as the inverse of matrix A
inverse=[[A[0][3],A[0][4],A[0][5]],
         [A[1][3],A[1][4],A[1][5]],
         [A[2][3],A[2][4],A[2][5]]]
print(f'Final result is:{inverse}')

Minor Matrix:[[1, 2], [4, 5]]
Minor of 9 is:[-3]
Cofactor is:[-3]

After rearranging :[1, 0, 0, 0, 0, 1]
After rearranging :[0, 1, 0, -2, 1, 3]
After rearranging :[0, 0, 1, 3, -1, -5]

Final result is:[[0, 0, 1], [-2, 1, 3], [3, -1, -5]]


FINDING EIGENVALUES AND EIGENVECTOR --->(IMPORTANT)

In [6]:
A=[[4,1],
   [2,3]]
a,b=4,1
c,d=2,3

#λ

#charactestic equation
#λ**2-(a+d)λ+(a-bc)

trace=a+d
det=a*d-b*c
print(f'characteristic equation is:λ²-{trace}λ+{det}')

#Solving quadratic to determine the eigen values
#b**2-4ac
desc=trace**2-(4*det)
lambda1=(trace+(desc)**0.5)/2
lambda2=(trace-(desc)**0.5)/2
print(f'Lambda 1:{lambda1}',
      f'\nlambda 2:{lambda2}')
#TO find eigenvector initilise value for x to find value for y
x1=1
print()
y1=-((a-lambda1)*x1)/b
Eigenvector1=[x1,y1]


print()
x2=1
y2=-((c-lambda2)*x2)/d
Eigenvector2=[x2,y2]

print(f'Eigen Vector 1:{Eigenvector1}',
      f'\nEigen Vector 2:{Eigenvector2}')


characteristic equation is:λ²-7λ+10
Lambda 1:5.0 
lambda 2:2.0


Eigen Vector 1:[1, 1.0] 
Eigen Vector 2:[1, -0.0]


FINDING COVARIANCE OF 2*2 MATRIX

In [8]:
height=[170,175,180]
weight=[65,70,75]

mean_height=sum(height)/len(height)
mean_weight=sum(weight)/len(weight)

var_height=0
var_weight=0
cov=0

for i in range(len(height)):
    var_height+=(height[i]-mean_height)**2
    var_weight+=(weight[i]-mean_weight)**2
    cov+=((height[i]-mean_height)*(weight[i]-mean_weight))
var_height=var_height/(len(height)-1)
var_weight=var_weight/(len(height)-1)
cov=cov/(len(height)-1)

cov_matrix=[[cov,var_height],
            [var_weight,cov]]
print(f'Covariance matrix is:{cov_matrix}')

Covariance matrix is:[[25.0, 25.0], [25.0, 25.0]]


PCA(PRINCIPAL COMPONENT ANALYSIS)--->(IMPORTANT)

In [ ]:
import numpy as np

X = np.array([
    [90, 88, 91],
    [80, 82, 79],
    [70, 68, 72],
    [60, 62, 61]
])

#s1:MEAN
mean=np.mean(X,axis=0)
print(f'Mean is:{mean}')

#s2:CENTER DATA
X_centered=X-mean
print()
print(f'Centered Data is:{X_centered}')

#s3:COVARIANCE MATRIX
print()
cov_matrix=np.cov(X_centered.T)
print(f'Covarience Matrix:{cov_matrix}')

#s4:EIGEN VALUES?VECTORS
Eigenvalues,Eigenvectors=np.linalg.eig(cov_matrix)
print()
print(f'Eigen Values:{Eigenvalues}',
      f'\nEigen Vectors:{Eigenvectors}')

#s5:Sorting them
idx=np.argsort(Eigenvalues)[::-1]
Eigenvalues=Eigenvalues[idx]
Eigenvectors=Eigenvectors[:,idx]
print()
print(f'Sorted Eigen VEctors are:{Eigenvectors}')
print()

#s6:Display principal Component
w=Eigenvectors[:,0]
print(f'Principal Component:{w}')

#s7:Print final result
print()
z=X_centered*w
print(f'PCA result is:{z}')

Mean is:[75.   75.   75.75]

Centered Data is:[[ 15.    13.    15.25]
 [  5.     7.     3.25]
 [ -5.    -7.    -3.75]
 [-15.   -13.   -14.75]]

Covarience Matrix:[[166.66666667 153.33333333 161.66666667]
 [153.33333333 145.33333333 146.33333333]
 [161.66666667 146.33333333 158.25      ]]

Eigen Values:[4.64795062e+02 2.34734973e-02 5.43146410e+00] 
Eigen Vectors:[[ 0.59865687  0.79245554  0.11672261]
 [ 0.55284631 -0.30332965 -0.77611344]
 [ 0.57962997 -0.52915531  0.6196965 ]]

Sorted Eigen VEctors are:[[ 0.59865687  0.11672261  0.79245554]
 [ 0.55284631 -0.77611344 -0.30332965]
 [ 0.57962997  0.6196965  -0.52915531]]

Principal Component:[0.59865687 0.55284631 0.57962997]

PCA result is:[[ 8.9798531   7.18700208  8.83935703]
 [ 2.99328437  3.8699242   1.8837974 ]
 [-2.99328437 -3.8699242  -2.17361238]
 [-8.9798531  -7.18700208 -8.54954205]]


GRADIENT DESCEND -->(IMPORTANT)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

x=np.array([1,2,3,4,5])
y=np.array([20,40,60,80,100])
#y=wx+b
w=0
b=0
learning_rate=0.01
epochs=1000

#Learning model
for epoch in range(epochs):
    #implementing prediction
    y_pred=w*x+b
    error=y_pred-y
    #fiding error
    cost=np.mean(error**2)

    dw=(2/len(x))*np.sum(error*x)
    db=(2/len(y))*np.sum(error)

    w=w-learning_rate*dw
    b=b-learning_rate*db

print(f'Weight:{w}')
print(f'Bias:{b}')
print(f'Cost:{cost}')

plt.figure()
plt.scatter(x,y)
plt.plot(x,w*x+b)
plt.title("REPORT")
plt.xlabel("Study hours")
plt.ylabel("Marks")
plt.show()


Weight: 1.9952
Bias: 0.0174
Cost: 5.5e-05


PRODUCT,QUOTIENT AND CHAIN RULE

In [10]:
# y = x²(x+1)(PRODUCT)
x=2
u=x**2
v=(x+1)
du=2*x
dv=1

dy=u*dv+v*du
print(f'Derivative1 is:{dy}')

#QUOTIENT
x=2
u=x**2
v=(x+1)
du=2*x
dv=1

dy=(v*(du)-u*(dv))/v**2
print(f'Derivative2 is:{dy}')

#CHAIN
# y = (x²+1)^5
x=2
u=x**2+1
outer=5*(u**4)
inner=2*x

dy=outer*inner
print(f'Derivative3 is:{dy}')

Derivative1 is:16
Derivative2 is:0.8888888888888888
Derivative3 is:12500
